development:
  dialect: mysql
  database: {{env "DATABASE_NAME"}}
  user: {{env "DATABASE_USER"}}
  password: {{env "DATABASE_PASSWORD"}}
  host: {{env "DATABASE_HOST"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/magento-service-consumer_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/magento-service-consumer_production?sslmode=disable"}}
